(function(){var h={},mt={},c={id:"affdf09dddabcdf2d681acefa474b973",dm:["mcbbs.net"],js:"tongji.baidu.com/hm-web/js/",etrk:[],cetrk:[],cptrk:[],icon:'/hmt/icon/21|gif|20|20',ctrk:["%5b%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fportal.php%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-mod-1.html%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-server-1.html%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-skin-1.html%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-texture-1.html%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-map-1.html%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-modpack-1.html%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-serverpack-1.html%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum.php%22%2c%22https%3a%5c%2f%5c%2fmcbbs.net%5c%2fforum-servermod-1.html%22%5d"],vdur:1800000,age:31536000000,qiao:0,pt:0,spa:0,aet:'',hca:'042F91391D3B3A32',ab:0,apps:''};var t=void 0,v=!0,w=null,y=!1;mt.cookie={};mt.cookie.set=function(b,d,a){var e;a.P&&(e=new Date,e.setTime(e.getTime()+a.P));document.cookie=b+"="+d+(a.domain?"; domain="+a.domain:"")+(a.path?"; path="+a.path:"")+(e?"; expires="+e.toGMTString():"")+(a.Gc?"; secure":"")};mt.cookie.get=function(b){return(b=RegExp("(^| )"+b+"=([^;]*)(;|$)").exec(document.cookie))?b[2]:w};
mt.cookie.ic=function(b,d){try{var a="Hm_ck_"+ +new Date;mt.cookie.set(a,"42",{domain:b,path:d,P:t});var e="42"===mt.cookie.get(a)?"1":"0";mt.cookie.set(a,"",{domain:b,path:d,P:-1});return e}catch(g){return"0"}};mt.lang={};mt.lang.o=function(b,d){return"[object "+d+"]"==={}.toString.call(b)};mt.lang.n=function(b){return mt.lang.o(b,"Function")};mt.lang.h=function(b){return mt.lang.o(b,"Object")};mt.lang.Ua=function(b){return mt.lang.o(b,"Number")&&isFinite(b)};
mt.lang.I=function(b){return mt.lang.o(b,"String")};mt.lang.isArray=function(b){return mt.lang.o(b,"Array")};mt.lang.g=function(b){return b.replace?b.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):b};mt.lang.trim=function(b){return b.replace(/^\s+|\s+$/g,"")};mt.lang.find=function(b,d,a){if(mt.lang.isArray(b)&&mt.lang.n(d))for(var e=b.length,g=0;g<e;g++)if(g in b&&d.call(a||b,b[g],g))return b[g];return w};mt.lang.H=function(b,d){return mt.lang.find(b,function(a){return a===d})!=w};
mt.lang.filter=function(b,d){var a=-1,e=0,g=b==w?0:b.length,q=[];if(mt.lang.n(d))for(;++a<g;){var f=b[a];d(f,a,b)&&(q[e++]=f)}return q};mt.lang.unique=function(b,d){var a=b.length,e=b.slice(0),g,q;for(mt.lang.n(d)||(d=function(e,a){return e===a});0<--a;){q=e[a];for(g=a;g--;)if(d(q,e[g])){e.splice(a,1);break}}return e};
mt.lang.Fc=function(b,d){function a(a){a=(e+e+Number(a).toString(2)).slice(-64);return[parseInt(a.slice(0,32),2),parseInt(a.slice(-32),2)]}var e="00000000000000000000000000000000",g=a(b),q=a(d);return parseInt((e+((g[0]|q[0])>>>0).toString(2)).slice(-32)+(e+((g[1]|q[1])>>>0).toString(2)).slice(-32),2)};mt.url={};mt.url.i=function(b,d){var a=b.match(RegExp("(^|&|\\?|#)("+d+")=([^&#]*)(&|$|#)",""));return a?a[3]:w};
mt.url.Mb=function(b){return(b=b.match(/^(https?:\/\/)?([^\/\?#]*)/))?b[2].replace(/.*@/,""):w};mt.url.ya=function(b){return(b=mt.url.Mb(b))?b.replace(/:\d+$/,""):b};mt.url.fc=function(b){var d=document.location.href,d=d.replace(/^https?:\/\//,"");return 0===d.indexOf(b)};mt.url.gc=function(b,d){b="."+b.replace(/:\d+/,"");d="."+d.replace(/:\d+/,"");var a=b.indexOf(d);return-1<a&&a+d.length===b.length};
(function(){var b=mt.lang,d=mt.url;mt.e={};mt.e.Eb=function(a){return document.getElementById(a)};mt.e.wa=function(a){if(!a)return w;try{a=String(a);if(0===a.indexOf("!HMCQ!"))return a;if(0===a.indexOf("!HMCC!"))return document.querySelector(a.substring(6,a.length));for(var e=a.split(">"),b=document.body,d=e.length-1;0<=d;d--)if(-1<e[d].indexOf("#")){var f=e[d].split("#")[1];(b=document.getElementById(f))||(b=document.getElementById(decodeURIComponent(f)));e=e.splice(d+1,e.length-(d+1));break}for(a=
0;b&&a<e.length;){var k=String(e[a]).toLowerCase();if(!("html"===k||"body"===k)){var d=0,r=e[a].match(/\[(\d+)\]/i),f=[];if(r)d=r[1]-1,k=k.split("[")[0];else if(1!==b.childNodes.length){for(var p=0,u=0,n=b.childNodes.length;u<n;u++){var l=b.childNodes[u];1===l.nodeType&&l.nodeName.toLowerCase()===k&&p++;if(1<p)return w}if(1!==p)return w}for(p=0;p<b.childNodes.length;p++)1===b.childNodes[p].nodeType&&b.childNodes[p].nodeName.toLowerCase()===k&&f.push(b.childNodes[p]);if(!f[d])return w;b=f[d]}a++}return b}catch(s){return w}};
mt.e.Pa=function(a,e){var b=[],d=[];if(!a)return d;for(;a.parentNode!=w;){for(var f=0,k=0,r=a.parentNode.childNodes.length,p=0;p<r;p++){var u=a.parentNode.childNodes[p];if(u.nodeName===a.nodeName&&(f++,u===a&&(k=f),0<k&&1<f))break}if((r=""!==a.id)&&e){b.unshift("#"+encodeURIComponent(a.id));break}else r&&(r="#"+encodeURIComponent(a.id),r=0<b.length?r+">"+b.join(">"):r,d.push(r)),b.unshift(encodeURIComponent(String(a.nodeName).toLowerCase())+(1<f?"["+k+"]":""));a=a.parentNode}d.push(b.join(">"));return d};
mt.e.ia=function(a){return(a=mt.e.Pa(a,v))&&a.length?String(a[0]):""};mt.e.Pb=function(a){return mt.e.Pa(a,y)};mt.e.Ma=function(a){var e;for(e="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==e)return a;return w};mt.e.Ib=function(a){return 9===a.nodeType?a:a.ownerDocument||a.document};mt.e.Na=function(a){var e={top:0,left:0};if(!a)return e;var b=mt.e.Ib(a).documentElement;"undefined"!==typeof a.getBoundingClientRect&&(e=a.getBoundingClientRect());return{top:e.top+(window.pageYOffset||b.scrollTop)-
(b.clientTop||0),left:e.left+(window.pageXOffset||b.scrollLeft)-(b.clientLeft||0)}};mt.e.getAttribute=function(a,e){var b=a.getAttribute&&a.getAttribute(e)||w;if(!b&&a.attributes&&a.attributes.length)for(var d=a.attributes,f=d.length,k=0;k<f;k++)d[k].nodeName===e&&(b=d[k].nodeValue);return b};mt.e.S=function(a){var e="document";a.tagName!==t&&(e=a.tagName);return e.toLowerCase()};mt.e.Sb=function(a){var e="";a.textContent?e=b.trim(a.textContent):a.innerText&&(e=b.trim(a.innerText));e&&(e=e.replace(/\s+/g,
" ").substring(0,255));return e};mt.e.R=function(a,e){var g;b.I(a)&&0===String(a).indexOf("!HMCQ!")?(g=String(a),g=d.i(document.location.href,g.substring(6,g.length))):b.I(a)||(g=mt.e.S(a),"input"===g&&e&&("button"===a.type||"submit"===a.type)?g=b.trim(a.value)||"":"input"===g&&!e&&"password"!==a.type?g=b.trim(a.value)||"":"img"===g?(g=mt.e.getAttribute,g=g(a,"alt")||g(a,"title")||g(a,"src")):g="body"===g||"html"===g?["(hm-default-content-for-",g,")"].join(""):mt.e.Sb(a));return String(g||"").substring(0,
255)};(function(){(mt.e.nc=function(){function a(){if(!a.ka){a.ka=v;for(var b=0,e=d.length;b<e;b++)d[b]()}}function e(){try{document.documentElement.doScroll("left")}catch(b){setTimeout(e,1);return}a()}var b=y,d=[],f;document.addEventListener?f=function(){document.removeEventListener("DOMContentLoaded",f,y);a()}:document.attachEvent&&(f=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",f),a())});(function(){if(!b)if(b=v,"complete"===document.readyState)a.ka=v;
else if(document.addEventListener)document.addEventListener("DOMContentLoaded",f,y),window.addEventListener("load",a,y);else if(document.attachEvent){document.attachEvent("onreadystatechange",f);window.attachEvent("onload",a);var d=y;try{d=window.frameElement==w}catch(r){}document.documentElement.doScroll&&d&&e()}})();return function(b){a.ka?b():d.push(b)}}()).ka=y})();return mt.e})();mt.event={};
mt.event.d=function(b,d,a){b.attachEvent?b.attachEvent("on"+d,function(e){a.call(b,e)}):b.addEventListener&&b.addEventListener(d,a,y)};
(function(){var b=mt.event;mt.f={};mt.f.Ba=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.f.cookieEnabled=navigator.cookieEnabled;mt.f.javaEnabled=navigator.javaEnabled();mt.f.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.f.pc=(window.screen.width||0)+"x"+(window.screen.height||0);mt.f.colorDepth=window.screen.colorDepth||0;mt.f.Rb=function(){var b;b=b||document;return parseInt(window.pageYOffset||b.documentElement.scrollTop||b.body&&
b.body.scrollTop||0,10)};mt.f.Ra=function(){var b=document;return parseInt(window.innerHeight||b.documentElement.clientHeight||b.body&&b.body.clientHeight||0,10)};mt.f.G=function(){return mt.f.Rb()+mt.f.Ra()};mt.f.ib=0;mt.f.Tb=function(){var b=document;return parseInt(window.innerWidth||b.documentElement.clientWidth||b.body.offsetWidth||0,10)};mt.f.orientation=0;(function(){function d(){var b=0;window.orientation!==t&&(b=window.orientation);screen&&(screen.orientation&&screen.orientation.angle!==
t)&&(b=screen.orientation.angle);mt.f.orientation=b;mt.f.ib=mt.f.Tb()}d();b.d(window,"orientationchange",d)})();return mt.f})();mt.B={};mt.B.parse=function(b){return(new Function("return ("+b+")"))()};
mt.B.stringify=function(){function b(b){/["\\\x00-\x1f]/.test(b)&&(b=b.replace(/["\\\x00-\x1f]/g,function(b){var e=a[b];if(e)return e;e=b.charCodeAt();return"\\u00"+Math.floor(e/16).toString(16)+(e%16).toString(16)}));return'"'+b+'"'}function d(b){return 10>b?"0"+b:b}var a={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(e){switch(typeof e){case "undefined":return"undefined";case "number":return isFinite(e)?String(e):"null";case "string":return b(e);case "boolean":return String(e);
default:if(e===w)return"null";if(e instanceof Array){var a=["["],q=e.length,f,k,r;for(k=0;k<q;k++)switch(r=e[k],typeof r){case "undefined":case "function":case "unknown":break;default:f&&a.push(","),a.push(mt.B.stringify(r)),f=1}a.push("]");return a.join("")}if(e instanceof Date)return'"'+e.getFullYear()+"-"+d(e.getMonth()+1)+"-"+d(e.getDate())+"T"+d(e.getHours())+":"+d(e.getMinutes())+":"+d(e.getSeconds())+'"';f=["{"];k=mt.B.stringify;for(q in e)if(Object.prototype.hasOwnProperty.call(e,q))switch(r=
e[q],typeof r){case "undefined":case "unknown":case "function":break;default:a&&f.push(","),a=1,f.push(k(q)+":"+k(r))}f.push("}");return f.join("")}}}();mt.localStorage={};mt.localStorage.ra=function(){if(!mt.localStorage.j)try{mt.localStorage.j=document.createElement("input"),mt.localStorage.j.type="hidden",mt.localStorage.j.style.display="none",mt.localStorage.j.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.j)}catch(b){return y}return v};
mt.localStorage.set=function(b,d,a){var e=new Date;e.setTime(e.getTime()+(a||31536E6));try{window.localStorage?(d=e.getTime()+"|"+d,window.localStorage.setItem(b,d)):mt.localStorage.ra()&&(mt.localStorage.j.expires=e.toUTCString(),mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.setAttribute(b,d),mt.localStorage.j.save(document.location.hostname))}catch(g){}};
mt.localStorage.get=function(b){if(window.localStorage){if(b=window.localStorage.getItem(b)){var d=b.indexOf("|"),a=b.substring(0,d)-0;if(a&&a>(new Date).getTime())return b.substring(d+1)}}else if(mt.localStorage.ra())try{return mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.getAttribute(b)}catch(e){}return w};
mt.localStorage.remove=function(b){if(window.localStorage)window.localStorage.removeItem(b);else if(mt.localStorage.ra())try{mt.localStorage.j.load(document.location.hostname),mt.localStorage.j.removeAttribute(b),mt.localStorage.j.save(document.location.hostname)}catch(d){}};mt.sessionStorage={};mt.sessionStorage.set=function(b,d){try{window.sessionStorage&&window.sessionStorage.setItem(b,d)}catch(a){}};
mt.sessionStorage.get=function(b){try{return window.sessionStorage?window.sessionStorage.getItem(b):w}catch(d){return w}};mt.sessionStorage.remove=function(b){try{window.sessionStorage&&window.sessionStorage.removeItem(b)}catch(d){}};
(function(){var b=mt.B;mt.N={};mt.N.log=function(b,a){var e=new Image,g="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[g]=e;e.onload=function(){e.onload=w;e=window[g]=w;a&&a(b)};e.src=b};mt.N.get=function(b,a){return mt.N.ob({url:b,method:"GET",data:a.data,timeout:a.timeout,noCache:v,success:a.success,fail:a.fail})};mt.N.ob=function(d){function a(m){var a=d[m];if(a)if(u&&clearTimeout(u),"success"!==m)a&&a(p);else{var e;try{e=b.parse(p.responseText)}catch(l){a&&a(p);return}a&&
a(p,e)}}d=d||{};var e=function(m){var b=[],a;for(a in m)m.hasOwnProperty(a)&&b.push(encodeURIComponent(a)+"="+encodeURIComponent(m[a]));return b.join("&")}(d.data||{}),g=d.url,q=(d.method||"GET").toUpperCase(),f=d.headers||{},k=d.timeout||0,r=d.noCache||y,p,u;try{a:if(window.XMLHttpRequest)p=new XMLHttpRequest;else{try{p=new ActiveXObject("Microsoft.XMLHTTP");break a}catch(n){}p=t}"GET"===q&&(e&&(g+=(0<=g.indexOf("?")?"&":"?")+e,e=w),r&&(g+=(0<=g.indexOf("?")?"&":"?")+"b"+ +new Date+"=1"));p.open(q,
g,v);p.onreadystatechange=function(){if(4===p.readyState){var m=0;try{m=p.status}catch(b){a("fail");return}200<=m&&300>m||304===m||1223===m?a("success"):a("fail")}};for(var l in f)f.hasOwnProperty(l)&&p.setRequestHeader(l,f[l]);k&&(u=setTimeout(function(){p.onreadystatechange=function(){};p.abort();a("fail")},k));p.send(e)}catch(s){a("fail")}return p};return mt.N})();
h.z={$b:"http://tongji.baidu.com/hm-web/welcome/ico",Fa:"hm.baidu.com/hm.gif",pb:/^(tongji|hmcdn).baidu.com$/,yc:"tongji.baidu.com",Xb:"hmmd",Yb:"hmpl",Bc:"utm_medium",Wb:"hmkw",Dc:"utm_term",Ub:"hmci",Ac:"utm_content",Zb:"hmsr",Cc:"utm_source",Vb:"hmcu",zc:"utm_campaign",Va:0,O:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",la:"https:",vb:6E5,qc:5E3,wb:5,da:1024,Y:2147483647,hb:"hca cc cf ci ck cl cm cp cu cw ds vl ep et ja ln lo lt rnd si su v cv lv api sn r ww p ct u tt".split(" "),
U:v,Ia:{id:"data-hm-id",ca:"data-hm-class",ba:"data-hm-xpath",content:"data-hm-content",oa:"data-hm-tag",link:"data-hm-link"},Ka:"data-hm-enabled",Ja:"data-hm-disabled",lc:"https://hmcdn.baidu.com/static/tongji/plugins/",bb:["UrlChangeTracker"]};(function(){var b={F:{},d:function(b,a){this.F[b]=this.F[b]||[];this.F[b].push(a)},L:function(b,a){this.F[b]=this.F[b]||[];for(var e=this.F[b].length,g=0;g<e;g++)this.F[b][g](a)}};return h.t=b})();
(function(){var b=mt.lang,d=/^https?:\/\//,a={Hb:function(b){var a;try{a=JSON.parse(decodeURIComponent(b[0]))}catch(d){}return a},Wa:function(b,d){return a.Xa(h.c&&h.c.b&&h.c.b.u,b,d)||a.Xa(document.location.href,b,d)},Xa:function(b,a,q){if(b===t)return y;d.test(a)||(b=b.replace(d,""));a=a.replace(/\/$/,"");b=b.replace(/\/$/,"");q&&(b=b.replace(/^(https?:\/\/)?www\./,"$1"));return RegExp("^"+a.replace(/[?.+^${}()|[\]\\]/g,"\\$&").replace(/\*/g,".*")+"$").test(b)},Q:function(e,d){var q=a.Hb(e);if(!b.o(q,
"Undefined")){if(b.isArray(q)){for(var f=0;f<q.length;f++)if(a.Wa(q[f],d))return v;return y}if(b.h(q)){var f=[],k;for(k in q)q.hasOwnProperty(k)&&a.Wa(k,d)&&(f=f.concat(q[k]));return f}}}};return h.fa=a})();
(function(){function b(b,e){var g=document.createElement("script");g.charset="utf-8";d.n(e)&&(g.readyState?g.onreadystatechange=function(){if("loaded"===g.readyState||"complete"===g.readyState)g.onreadystatechange=w,e()}:g.onload=function(){e()});g.src=b;var q=document.getElementsByTagName("script")[0];q.parentNode.insertBefore(g,q)}var d=mt.lang;return h.load=b})();
(function(){var b=h.z,d={init:function(){if(""!==c.icon){var a=c.icon.split("|"),e=b.$b+"?s="+c.id,d="https://hmcdn.baidu.com/static"+a[0]+".gif";document.write("swf"===a[1]||"gif"===a[1]?'<a href="'+e+'" target="_blank"><img border="0" src="'+d+'" width="'+a[2]+'" height="'+a[3]+'"></a>':'<a href="'+e+'" target="_blank">'+a[0]+"</a>")}}};h.t.d("pv-b",d.init);return d})();
(function(){var b=mt.url,d=mt.cookie,a=mt.localStorage,e=mt.sessionStorage,g={getData:function(b){try{return d.get(b)||e.get(b)||a.get(b)}catch(g){}},setData:function(b,f,k){try{d.set(b,f,{domain:g.ha(),path:g.va(),P:k}),k?a.set(b,f,k):e.set(b,f)}catch(r){}},removeData:function(b){try{d.set(b,"",{domain:g.ha(),path:g.va(),P:-1}),e.remove(b),a.remove(b)}catch(f){}},ha:function(){for(var a=document.location.hostname,e=0,d=c.dm.length;e<d;e++)if(b.gc(a,c.dm[e]))return c.dm[e].replace(/(:\d+)?[/?#].*/,
"");return a},va:function(){for(var a=0,e=c.dm.length;a<e;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&b.fc(d))return d.replace(/^[^/]+(\/.*)/,"$1")+"/"}return"/"}};return h.ea=g})();
(function(){var b=mt.lang,d=mt.B,a=h.ea,e={pageview:{},session:{},autoEventTracking:{},customEvent:{},user:{}},g={user:1,session:2,pageview:3,autoEventTracking:3,customEvent:3,others:3},q=["session","user"],f="Hm_up_"+c.id,k={init:function(){k.dc()},dc:function(){try{var r=d.parse(decodeURIComponent(a.getData(f)));b.h(r)&&(e.user=r)}catch(p){}},A:function(b){var a={};e[b]!==t&&(a=e[b]);b=this.za();for(var d in a)a.hasOwnProperty(d)&&(b[d]=a[d]);return b},za:function(){for(var b={},a,d=q.length-1;0<=
d;d--){a=e[q[d]];for(var n in a)a.hasOwnProperty(n)&&(b[n]=a[n])}return b},setProperty:function(a,p,g){var n=e[a];if(b.h(n)&&b.h(p)){for(var l in p)if(p.hasOwnProperty(l)){var f=b.g(String(l));if(g||!/^_/.test(f)&&!/_$/.test(f)||/^(_iden|ei_|ec_|ex_|en_|et_|el_)$/.test(f)){var m=p[l];if(m==w)delete n[f];else{if(b.h(m)||b.isArray(m))m=d.stringify(m);m=b.g(String(m));k.hc(a,f,m)&&(n[f]={value:m,scope:k.Qa(a)})}}}"user"===a&&k.Da()}},s:function(a){a!==t&&("userId"===a&&b.h(e.user)?(delete e.user.uid_,
k.Da()):"user"===a&&b.h(e.user)?(a=e.user.uid_,e.user=a===t?{}:{uid_:a},k.Da()):e[a]!==t&&(e[a]={}))},Da:function(){try{a.setData(f,encodeURIComponent(d.stringify(e.user)),c.age)}catch(b){}},hc:function(b,a,d){var n=v,l=e[b];if(256<encodeURIComponent(String(a)).length||256<encodeURIComponent(String(d)).length)n=y;else{var g=l[a];l[a]={value:d,scope:k.Qa(b)};b=k.K(k.A(b));2048<encodeURIComponent(b).length&&(g!==t?l[a]=g:delete l[a],n=y)}return n},K:function(b){var a=[],e,d;for(d in b)b.hasOwnProperty(d)&&
(e=[d,b[d].value],(1===b[d].scope||2===b[d].scope)&&e.push(b[d].scope),a.push(e.join("*")));return a.join("!")},Qa:function(b){b=g[b];return b!==t?b:g.others}};return h.M=k})();
(function(){var b=mt.e,d=mt.lang,a=h.t,e=h.fa,g=h.M,q=g.K;if(d.isArray(c.cptrk)&&0<c.cptrk.length){var f={$a:{},pa:{},init:function(){for(var b,a=e.Q(c.cptrk)||[],p=0;p<a.length;p++)if(b=a[p],b.a!==t&&d.h(b.a)){b=b.a;for(var g in b)b.hasOwnProperty(g)&&(f.pa[g]=String(b[g]))}},Za:function(){var a,e,d;for(d in f.pa)if(f.pa.hasOwnProperty(d)&&f.$a[d]===t&&(a=f.pa[d],a=b.wa(a)))e=e===t?{}:e,e[d]=b.R(a,y),f.$a[d]=v;return e},Aa:function(){var b=f.Za();b&&f.sc(b)},bc:function(){"MutationObserver"in window&&
document.body?(new MutationObserver(f.Aa)).observe(document.body,{childList:v,subtree:v}):window.setInterval(f.Aa,15E3)},sc:function(b){if(d.h(b)){g.setProperty("pageview",b);b=h.c.b.p;var a=h.c.b.ep;h.c.b.et=9;h.c.b.ep="";h.c.b.p=q(g.A("pageview"));h.c.m();h.c.b.p=b;h.c.b.ep=a;g.s("pageview")}}};f.init();a.d("pv-b",function(){var b=f.Za();b&&g.setProperty("pageview",b)});f.bc();b.nc(f.Aa)}})();
(function(){var b=mt.lang,d=mt.e,a=h.fa,e={ga:function(b,q){return function(f){var k=f.target||f.srcElement;if(k){var r=a.Q(q)||[],p=k.getAttribute(b.qa);f=f.clientX+":"+f.clientY;if(p&&p===f)k.removeAttribute(b.qa);else if(0<r.length&&(k=d.Pb(k))&&k.length)if(r=k.length,p=k[k.length-1],1E4>r*p.split(">").length)for(p=0;p<r;p++)e.gb(b,k[p]);else e.gb(b,p)}}},gb:function(a,e){for(var d={},k=String(e).split(">").length,r=0;r<k;r++)d[e]="",e=e.substring(0,e.lastIndexOf(">"));a&&(b.h(a)&&a.La)&&a.La(d)},
oc:function(b,a){return function(e){(e.target||e.srcElement).setAttribute(b.qa,e.clientX+":"+e.clientY);b&&b.w&&(a?b.w(a):b.w("#"+encodeURIComponent(this.id),e.type))}}};return h.Ab=e})();
(function(){var b=mt.e,d=mt.event,a=mt.lang,e=h.z,g=h.fa,q=h.Ab,f=h.M,k=f.K,r={qa:"HM_ce",kb:function(){if(c.cetrk&&0<c.cetrk.length){d.d(document,"click",q.ga(r,c.cetrk));for(var a=g.Q(c.cetrk)||[],e=0,n=a.length;e<n;e++){var l=a[e],f=l.p||"";-1===f.indexOf(">")&&(0===f.indexOf("#")&&(f=f.substring(1)),(f=b.Eb(f))&&d.d(f,"click",q.oc(r,l)))}}},La:function(b){for(var a=g.Q(c.cetrk)||[],e=0;e<a.length;e++){var d=a[e],f=r.Kb(d.p,b);f&&r.w(d,f)}},Kb:function(b,a){b=String(b);if(0<b.indexOf("*")){var e=
RegExp("^"+b.replace(/\[/g,"\\[").replace(/\]/g,"\\]").replace(/\*/,"\\d+")+"$"),d;for(d in a)if(a.hasOwnProperty(d)&&e.test(d))return d;return w}return a.hasOwnProperty(b)?b:w},w:function(e,d){h.c.b.et=7;var n=e&&e.k||"",n=a.g(n),l={};if(e&&e.a&&a.h(e.a)){var g=e.a,m;for(m in g)if(g.hasOwnProperty(m)){var x=r.Qb(g[m]||"",d),x=x?b.R(x,y):"";l[m]=x}}l=r.Fb(l,d||e&&e.p);l._iden=n;f.setProperty("customEvent",l);h.c.b.ep="";h.c.b.p=k(f.A("customEvent"));h.c.m();h.c.b.p="";f.s("customEvent")},Fb:function(a,
d){var n=b.wa(d),l=e.Ia;n&&(c.aet&&c.aet.length?(a.ei_=b.getAttribute(n,l.id)||b.getAttribute(n,"id")||"",a.ec_=b.getAttribute(n,l.ca)||b.getAttribute(n,"class")||"",a.ex_=b.getAttribute(n,l.ba)||b.ia(n),a.en_=b.getAttribute(n,l.content)||b.R(n,v),a.et_=b.getAttribute(n,l.oa)||b.S(n),a.el_=b.getAttribute(n,l.link)||b.getAttribute(n,"href")||""):(a.ex_=b.getAttribute(n,l.ba)||b.ia(n),a.en_=b.getAttribute(n,l.content)||b.R(n,v)));return a},Qb:function(a,e){a=String(a);e=String(e);if(0<a.indexOf("*")){var d=
/.*\[(\d+)\]$/.exec(e);a=a.replace("*",d?d[1]:"1")}return b.wa(a)}};h.t.d("pv-b",r.kb);return r})();
(function(){var b=mt.e,d=mt.lang,a=mt.event,e=mt.f,g=h.z,q=h.fa,f=[],k={jb:function(){c.ctrk&&0<c.ctrk.length&&(a.d(document,"mouseup",k.ub()),a.d(window,"unload",function(){k.ma()}),setInterval(function(){k.ma()},g.vb))},ub:function(){return function(b){if(q.Q(c.ctrk,v)&&(b=k.Gb(b),""!==b)){var a=(g.la+"//"+g.Fa+"?"+h.c.fb().replace(/ep=[^&]*/,"ep="+encodeURIComponent(b))).length;a+(g.Y+"").length>g.da||(a+encodeURIComponent(f.join("!")+(f.length?"!":"")).length+(g.Y+"").length>g.da&&k.ma(),f.push(b),
(f.length>=g.wb||/\*a\*/.test(b))&&k.ma())}}},Gb:function(a){var f=a.target||a.srcElement,g,n;e.Ba?(n=Math.max(document.documentElement.scrollTop,document.body.scrollTop),g=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),g=a.clientX+g,n=a.clientY+n):(g=a.pageX,n=a.pageY);a=k.Nb(a,f,g,n);var l=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:g-=l/2;break;case 2:g-=l}l=[];l.push(g);l.push(n);l.push(a.X);l.push(a.Z);l.push(a.mc);
l.push(d.g(a.kc));l.push(a.aa);l.push(a.T);(f="a"===(f.tagName||"").toLowerCase()?f:b.Ma(f))?(l.push("a"),l.push(d.g(encodeURIComponent(f.href)))):l.push("b");return l.join("*")},Nb:function(a,g,f,n){a=b.ia(g);var l=0,k=0,m=0,x=0;if(g&&(l=g.offsetWidth||g.clientWidth,k=g.offsetHeight||g.clientHeight,x=b.Na(g),m=x.left,x=x.top,d.n(g.getBBox)&&(k=g.getBBox(),l=k.width,k=k.height),"html"===(g.tagName||"").toLowerCase()))l=Math.max(l,g.clientWidth),k=Math.max(k,g.clientHeight);return{X:Math.round(100*
((f-m)/l)),Z:Math.round(100*((n-x)/k)),mc:e.orientation,kc:a,aa:l,T:k}},ma:function(){0!==f.length&&(h.c.b.et=2,h.c.b.ep=f.join("!"),h.c.m(),f=[])}};h.t.d("pv-b",k.jb);return k})();
(function(){var b=mt.lang,d=mt.e,a=mt.event,e=mt.f,g=h.z,q=h.t,f=h.M,k=f.K,r=+new Date,p=[],u={ga:function(){return function(a){if(h.c&&h.c.U&&c.aet&&c.aet.length){var e=a.target||a.srcElement;if(e){var f=h.c.rb,m=d.getAttribute(e,g.Ka)!=w?v:y;if(d.getAttribute(e,g.Ja)==w)if(m)u.sa(u.xa(e,a));else{var x=d.S(e);if(b.H(f,"*")||b.H(f,x))u.sa(u.xa(e,a));else for(;e.parentNode!=w;){var m=e.parentNode,x=d.S(m),z="a"===x&&b.H(f,"a")?v:y,x="button"===x&&b.H(f,"button")?v:y,k=d.getAttribute(m,g.Ka)!=w?v:y;
if(d.getAttribute(m,g.Ja)==w&&(z||x||k)){u.sa(u.xa(m,a));break}e=e.parentNode}}}}}},xa:function(a,l){var f={},m=g.Ia;f.id=d.getAttribute(a,m.id)||d.getAttribute(a,"id")||"";f.ca=d.getAttribute(a,m.ca)||d.getAttribute(a,"class")||"";f.ba=d.getAttribute(a,m.ba)||d.ia(a);f.content=d.getAttribute(a,m.content)||d.R(a,v);f.oa=d.getAttribute(a,m.oa)||d.S(a);f.link=d.getAttribute(a,m.link)||d.getAttribute(a,"href")||"";f.type=l.type||"click";m=b.Ua(a.offsetTop)?a.offsetTop:0;"click"===l.type?m=e.Ba?l.clientY+
Math.max(document.documentElement.scrollTop,document.body.scrollTop):l.pageY:"touchend"===l.type&&(l.Ya&&l.Ya.changedTouches)&&(m=l.Ya.changedTouches[0].pageY);f.xc=m;m=this.Jb(l);f.X=m.X||0;f.Z=m.Z||0;f.aa=m.aa||0;f.T=m.T||0;f.Ga=m.Ga||"b";return f},Jb:function(a){var f=a.target||a.srcElement,g;if(e.Ba){var m=Math.max(document.documentElement.scrollTop,document.body.scrollTop);g=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft);g=a.clientX+g;a=a.clientY+m}else g=a.pageX,a=a.pageY;
var x=m=0,z=0,k=0;if(f&&(m=f.offsetWidth||f.clientWidth,x=f.offsetHeight||f.clientHeight,k=d.Na(f),z=k.left,k=k.top,b.n(f.getBBox)&&(x=f.getBBox(),m=x.width,x=x.height),"html"===(f.tagName||"").toLowerCase()))m=Math.max(m,f.clientWidth),x=Math.max(x,f.clientHeight);return{X:Math.round(100*((g-z)/m)),Z:Math.round(100*((a-k)/x)),aa:m,T:x,Ga:("a"===(f.tagName||"").toLowerCase()?f:d.Ma(f))?"a":"b"}},sa:function(a){var e=b.g;a=[+new Date-(h.c.V!==t?h.c.V:r),e(a.id),e(a.ca),e(a.oa),e(a.ba),e(a.link),e(a.content),
a.type,a.xc,a.X,a.Z,a.aa,a.T,a.Ga].join("*");u.ta(a);b.n(this.$())&&this.$()()},ta:function(a){var b=g.da;a.length>b||(encodeURIComponent(p.join("!")+a).length>b&&0<p.length&&(u.w(p.join("!")),p=[]),p.push(a))},w:function(a){h.c.b.et=5;h.c.b.ep=a;f.setProperty("autoEventTracking",{view_h_:e.G()},v);h.c.b.p=k(f.A("autoEventTracking"));h.c.m();h.c.b.p="";f.setProperty("autoEventTracking",{view_h_:w},v)},$:function(){return function(){p&&p.length&&(u.w(p.join("!")),p=[])}}};b.I(c.aet)&&""!==c.aet&&q.d("pv-b",
function(){a.d(document,"click",u.ga());"ontouchend"in document&&a.d(window,"touchend",u.ga());a.d(window,"unload",u.$())});return u})();
(function(){var b=mt.lang,d=mt.event,a=mt.f,e=h.z,g=h.t,q=h.M,f=q.K,k=+new Date,r=[],p=w,u={mb:function(){b.I(c.aet)&&""!==c.aet&&setInterval(u.eb,e.qc)},eb:function(){var b=a.G();0<b-h.c.b.vl&&(h.c.b.vl=b)}},n={zb:function(){return function(){h.c&&(h.c.U&&c.aet&&c.aet.length)&&(window.clearTimeout(p),p=window.setTimeout(function(){n.lb(a.G())},150))}},lb:function(a){n.ta([+new Date-(h.c.V!==t?h.c.V:k),a].join("*"))},ta:function(a){if(encodeURIComponent(r.join("!")+a).length>e.da||3<r.length)n.w(r.join("!")),
r=[];r.push(a)},w:function(b){u.eb();h.c.b.et=6;h.c.b.vh=a.Ra();h.c.b.ep=b;q.setProperty("autoEventTracking",{view_h_:a.G()},v);h.c.b.p=f(q.A("autoEventTracking"));h.c.m();h.c.b.p="";q.setProperty("autoEventTracking",{view_h_:w},v)},$:function(){return function(){r&&r.length&&(n.w(r.join("!")),r=[])}}};b.I(c.aet)&&""!==c.aet&&g.d("pv-b",function(){d.d(window,"scroll",n.zb());d.d(window,"unload",n.$());u.mb()});return n})();
(function(){function b(){return function(){h.c.b.et=3;h.c.b.ep=h.ua.Ob()+","+h.ua.Lb();h.c.b.hca=c.hca;h.c.m()}}function d(){clearTimeout(z);var a;m&&(a="visible"==document[m]);x&&(a=!document[x]);k="undefined"==typeof a?v:a;if((!f||!r)&&k&&p)s=v,n=+new Date;else if(f&&r&&(!k||!p))s=y,l+=+new Date-n;f=k;r=p;z=setTimeout(d,100)}function a(a){var b=document,m="";if(a in b)m=a;else for(var e=["webkit","ms","moz","o"],d=0;d<e.length;d++){var f=e[d]+a.charAt(0).toUpperCase()+a.slice(1);if(f in b){m=f;
break}}return m}function e(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))p="focus"==a.type||"focusin"==a.type?v:y,d()}var g=mt.event,q=h.t,f=v,k=v,r=v,p=v,u=+new Date,n=u,l=0,s=v,m=a("visibilityState"),x=a("hidden"),z;d();(function(){var a=m.replace(/[vV]isibilityState/,"visibilitychange");g.d(document,a,d);g.d(window,"pageshow",d);g.d(window,"pagehide",d);"object"==typeof document.onfocusin?(g.d(document,"focusin",e),g.d(document,"focusout",e)):(g.d(window,"focus",e),g.d(window,
"blur",e))})();h.ua={Ob:function(){return+new Date-u},Lb:function(){return s?+new Date-n+l:l}};q.d("pv-b",function(){g.d(window,"unload",b())});q.d("duration-send",b());q.d("duration-done",function(){n=u=+new Date;l=0});return h.ua})();
(function(){var b=mt.lang,d=h.z,a=h.load,e=h.ea,g={ac:function(g){if((window._dxt===t||b.o(window._dxt,"Array"))&&"undefined"!==typeof h.c){var f=e.ha();a([d.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(f)].join(""),g)}},wc:function(a){if(b.o(a,"String")||b.o(a,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",a])}};return h.xb=g})();
(function(){function b(a,b,e,d){if(!(a===t||b===t||d===t)){if(""===a)return[b,e,d].join("*");a=String(a).split("!");for(var f,g=y,k=0;k<a.length;k++)if(f=a[k].split("*"),String(b)===f[0]){f[1]=e;f[2]=d;a[k]=f.join("*");g=v;break}g||a.push([b,e,d].join("*"));return a.join("!")}}function d(a){for(var b in a)if({}.hasOwnProperty.call(a,b)){var f=a[b];e.h(f)||e.isArray(f)?d(f):a[b]=String(f)}}var a=mt.url,e=mt.lang,g=mt.B,q=mt.f,f=h.z,k=h.t,r=h.xb,p=h.load,u=h.ea,n=h.M,l=n.K,s={W:[],na:0,Ca:y,D:{Ha:"",
page:""},init:function(){s.l=0;n.init();k.d("pv-b",function(){s.yb();s.Bb()});k.d("pv-d",function(){s.Cb();s.D.page=""});k.d("stag-b",function(){h.c.b.api=s.l||s.na?s.l+"_"+s.na:"";h.c.b.ct=[decodeURIComponent(u.getData("Hm_ct_"+c.id)||""),s.D.Ha,s.D.page].join("!")});k.d("stag-d",function(){h.c.b.api=0;s.l=0;s.na=0})},yb:function(){var a=window._hmt||[];if(!a||e.o(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,b=0;b<arguments.length;b++){var m=arguments[b];e.o(m,"Array")&&
(a.cmd[a.id].push(m),"_setAccount"===m[0]&&(1<m.length&&/^[0-9a-f]{31,32}$/.test(m[1]))&&(m=m[1],a.id=m,a.cmd[m]=a.cmd[m]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},Bb:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],e=/^_track(Event|MobConv|Order)$/,d=0,f=b.length;d<f;d++){var g=b[d];e.test(g[0])?s.W.push(g):s.Ea(g)}a.cmd[c.id]={push:s.Ea}},Cb:function(){if(0<s.W.length)for(var a=0,b=s.W.length;a<b;a++)s.Ea(s.W[a]);s.W=w},Ea:function(a){var b=
a[0];if(s.hasOwnProperty(b)&&e.n(s[b]))s[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{31,32}$/.test(a[1])&&(s.l|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],y===a||v===a))s.l|=2,h.c.Sa=a},_trackPageview:function(a){1<a.length&&(a[1].charAt&&"/"===a[1].charAt(0))&&(s.l|=4,h.c.b.sn=h.c.Oa(),h.c.b.et=0,h.c.b.ep="",h.c.b.vl=q.G(),s.Ca||(h.c.b.su=h.c.b.u||document.location.href),h.c.b.u=f.protocol+"//"+document.location.host+a[1],h.c.b.p=l(n.A("pageview")),h.c.m(),h.c.b.p="",h.c.V=
+new Date,n.s("pageview"))},_trackEvent:function(a){2<a.length&&(s.l|=8,h.c.b.et=4,h.c.b.ep=e.g(a[1])+"*"+e.g(a[2])+(a[3]?"*"+e.g(a[3]):"")+(a[4]?"*"+e.g(a[4]):""),h.c.b.p=l(n.za()),h.c.m(),h.c.b.p="")},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){s.na++;for(var f=(h.c.b.cv||"*").split("!"),g=f.length;g<b-1;g++)f.push("*");f[b-1]=d+"*"+e.g(a[2])+"*"+e.g(a[3]);h.c.b.cv=f.join("!");a=h.c.b.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==
a?u.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):u.removeData("Hm_cv_"+c.id)}}},_setUserTag:function(a){if(!(3>a.length)){var d=e.g(a[1]);a=e.g(a[2]);if(d!==t&&a!==t){var f=decodeURIComponent(u.getData("Hm_ct_"+c.id)||""),f=b(f,d,1,a);u.setData("Hm_ct_"+c.id,encodeURIComponent(f),c.age)}}},_setVisitTag:function(a){if(!(3>a.length)){var d=e.g(a[1]);a=e.g(a[2]);if(d!==t&&a!==t){var f=s.D.Ha,f=b(f,d,2,a);s.D.Ha=f}}},_setPageTag:function(a){if(!(3>a.length)){var d=e.g(a[1]);a=e.g(a[2]);if(d!==t&&
a!==t){var f=s.D.page,f=b(f,d,3,a);s.D.page=f}}},_setReferrerOverride:function(a){1<a.length&&(a=a[1],e.o(a,"String")?(h.c.b.su="/"===a.charAt(0)?f.protocol+"//"+window.location.host+a:a,s.Ca=v):s.Ca=y)},_trackOrder:function(a){a=a[1];e.h(a)&&(d(a),s.l|=16,h.c.b.et=94,h.c.b.ep=g.stringify(a),h.c.b.p=l(n.za()),h.c.m(),h.c.b.p="")},_setDataxId:function(a){a=a[1];r.ac();r.wc(a)},_setUserId:function(a){a=a[1];if(e.I(a)||e.Ua(a)){var b=n.A("user").uid_;if(!(b&&b.value===e.g(String(a)))){var b=h.c.b.p,
d=h.c.b.ep;h.c.b.et=8;h.c.b.ep="";h.c.b.p="uid_*"+e.g(String(a));h.c.m();var f={};f.uid_=a;n.setProperty("user",f,v);h.c.b.p=b;h.c.b.ep=d}}},_clearUserId:function(a){1<a.length&&v===a[1]&&n.s("userId")},_getClientId:function(a){a=a[1];e.n(a)&&c.hca!==t&&a(c.hca)},_setUserProperty:function(a){a=a[1];e.h(a)&&n.setProperty("user",a)},_clearUserProperty:function(a){1<a.length&&v===a[1]&&n.s("user")},_setSessionProperty:function(a){a=a[1];e.h(a)&&n.setProperty("session",a)},_clearSessionProperty:function(a){1<
a.length&&v===a[1]&&n.s("session")},_setPageviewProperty:function(a){a=a[1];e.h(a)&&n.setProperty("pageview",a)},_clearPageviewProperty:function(a){1<a.length&&v===a[1]&&n.s("pageview")},_setAutoEventTrackingProperty:function(a){a=a[1];e.h(a)&&n.setProperty("autoEventTracking",a)},_clearAutoEventTrackingProperty:function(a){1<a.length&&v===a[1]&&n.s("autoEventTracking")},_setAutoTracking:function(a){if(1<a.length&&(a=a[1],y===a||v===a))h.c.Ta=a},_setAutoEventTracking:function(a){if(1<a.length&&(a=
a[1],y===a||v===a))h.c.U=a},_trackPageDuration:function(a){1<a.length?(a=a[1],2===String(a).split(",").length&&(h.c.b.et=3,h.c.b.ep=a,h.c.m())):k.L("duration-send");k.L("duration-done")},_require:function(b){1<b.length&&(b=b[1],f.pb.test(a.ya(b))&&p(b))},_providePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1];a=a[2];if(e.H(f.bb,d)&&e.n(a)&&(b.plugins=b.plugins||{},b.J=b.J||{},b.plugins[d]=a,b.C=b.C||[],a=b.C.slice(),d&&a.length&&a[0][1]===d))for(var g=0,k=a.length;g<k;g++){var l=a[g][2]||
{};if(b.plugins[d]&&!b.J[d])b.J[d]=new b.plugins[d](l),b.C.shift();else break}}},_requirePlugin:function(a){if(1<a.length){var b=window._hmt,d=a[1],g=a[2]||{};if(e.H(f.bb,d))if(b.plugins=b.plugins||{},b.J=b.J||{},b.plugins[d]&&!b.J[d])b.J[d]=new b.plugins[d](g);else{b.C=b.C||[];for(var g=0,k=b.C.length;g<k;g++)if(b.C[g][1]===d)return;b.C.push(a);s._require([w,f.lc+d+".js"])}}},_fetchABTest:function(a){if(1<a.length&&(a=a[1],e.h(a))){var b=a.paramName,d=a.defaultValue,f=a.callback;h.ab&&(b&&d!==t&&
e.n(f))&&h.ab.Ec(b,function(a){f(a===w?d:a)})}},_trackCustomEvent:function(a){if(1<a.length){var b=a[1];a=a[2];e.h(a)||(a={});a._iden=b;n.setProperty("customEvent",a);h.c.b.et=7;h.c.b.ep="";h.c.b.p=l(n.A("customEvent"));h.c.m();h.c.b.p="";n.s("customEvent")}}};s.init();h.qb=s;return h.qb})();(function(){var b=h.t;c.spa!==t&&"1"===String(c.spa)&&(window._hmt=window._hmt||[],window._hmt.push(["_requirePlugin","UrlChangeTracker"]),b.d("pv-b",function(){""!==window.location.hash&&(h.c.b.u=window.location.href)}))})();
(function(){function b(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=v,this.b={},this.Ta=this.Sa=v,this.U=l.U,this.rb=e.I(c.aet)&&0<c.aet.length?c.aet.split(","):"",this.init())}var d=mt.url,a=mt.N,e=mt.lang,g=mt.cookie,q=mt.f,f=mt.sessionStorage,k=mt.B,r=mt.event,p=h.ea,u=h.M,n=u.K,l=h.z,s=h.load,m=h.t;b.prototype={uc:function(){var a,b,e,d;l.Va=p.getData("Hm_lpvt_"+c.id)||0;if(d=p.getData("Hm_lvt_"+c.id)){for(b=d.split(",");2592E3<l.O-b[0];)b.shift();e=4>b.length?
2:3;for(l.O-l.Va>c.vdur&&b.push(l.O);4<b.length;)b.shift();d=b.join(",");b=b[b.length-1]}else d=l.O,b="",e=1;this.ec()?(p.setData("Hm_lvt_"+c.id,d,c.age),p.setData("Hm_lpvt_"+c.id,l.O),a=g.ic(p.ha(),p.va())):this.Db();this.b.cc=a;this.b.lt=b;this.b.lv=e},ec:function(){var a=d.ya(document.location.href);return!e.H("sjh.baidu.com isite.baidu.com ls.wejianzhan.com bs.wejianzhan.com product.weijianzhan.com qianhu.weijianzhan.com aisite.wejianzhan.com".split(" "),a)},Db:function(){for(var a=document.cookie.split(";"),
b=0;b<a.length;b++){var d=a[b].split("=");d.length&&/Hm_(up|ct|cv|lp?vt)_[0-9a-f]{31}/.test(String(d[0]))&&p.removeData(d[0]);d.length&&/Hm_ck_[0-9]{13}/.test(String(d[0]))&&p.removeData(d[0])}},fb:function(){for(var a=[],b=this.b.et,d=0,e=l.hb.length;d<e;d++){var f=l.hb[d],g=this.b[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&("ct"!==f||"ct"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}return a.join("&")},vc:function(){this.uc();this.b.si=c.id;this.b.sn=this.Oa();this.b.su=
document.referrer;this.b.ds=q.pc;this.b.cl=q.colorDepth+"-bit";this.b.ln=String(q.language).toLowerCase();this.b.ja=q.javaEnabled?1:0;this.b.ck=q.cookieEnabled?1:0;this.b.lo="number"===typeof _bdhm_top?1:0;this.b.v="1.2.91";this.b.cv=decodeURIComponent(p.getData("Hm_cv_"+c.id)||"");this.b.tt=document.title||"";this.b.vl=q.G();var a=document.location.href;this.b.cm=d.i(a,l.Xb)||"";this.b.cp=d.i(a,l.Yb)||d.i(a,l.Bc)||"";this.b.cw=d.i(a,l.Wb)||d.i(a,l.Dc)||"";this.b.ci=d.i(a,l.Ub)||d.i(a,l.Ac)||"";this.b.cf=
d.i(a,l.Zb)||d.i(a,l.Cc)||"";this.b.cu=d.i(a,l.Vb)||d.i(a,l.zc)||"";/https?:/.test(document.location.protocol)&&(this.b.u=a)},init:function(){try{this.vc(),this.tc(),h.c=this,this.sb(),this.jc(),m.L("pv-b"),this.rc()}catch(b){var d=[];d.push("si="+c.id);d.push("n="+encodeURIComponent(b.name));d.push("m="+encodeURIComponent(b.message));d.push("r="+encodeURIComponent(document.referrer));a.log(l.la+"//"+l.Fa+"?"+d.join("&"))}},rc:function(){function a(){m.L("pv-d")}this.Sa?(this.b.et=0,this.b.ep="",
this.b.p=n(u.A("pageview")),this.b.vl=q.G(),this.m(a),this.b.p=""):a();this.V=+new Date;u.s("pageview")},m:function(b){if(this.Ta){var d=this;d.b.rnd=Math.round(Math.random()*l.Y);d.b.r=q.orientation;d.b.ww=q.ib;m.L("stag-b");var f=l.la+"//"+l.Fa+"?"+d.fb();m.L("stag-d");d.nb(f);a.log(f,function(a){d.cb(a);e.n(b)&&b.call(d)})}},sb:function(){try{if(window.postMessage&&window.self!==window.parent){var a=this;r.d(window,"message",function(b){if(d.ya(b.origin)===l.yc){b=b.data||{};var e=b.jn||"",f=/^customevent$|^heatmap$|^pageclick$|^select$/.test(e);
if(RegExp(c.id).test(b.sd||"")&&f)a.b.rnd=Math.round(Math.random()*l.Y),s(l.protocol+"//"+c.js+e+".js?"+a.b.rnd)}});window.parent.postMessage({id:c.id,url:document.location.href,status:"__Messenger__hmLoaded"},"*")}}catch(b){}},jc:function(){try{if(window.self===window.parent){var a=document.location.href,b=d.i(a,"baidu-analytics-token"),e=d.i(a,"baidu-analytics-jn");/^[a-f0-9]{32}\/?$/.test(b)&&/^overlay\/?$/.test(e)&&s(l.protocol+"//"+c.js+e+".js?"+Math.round(Math.random()*l.Y))}}catch(f){}},nb:function(a){var b;
try{b=k.parse(f.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}var e=this.b.u?"":"&u="+encodeURIComponent(document.location.href);b.push(a.replace(/^https?:\/\//,"")+e);f.set("Hm_unsent_"+c.id,k.stringify(b))},cb:function(a){var b;try{b=k.parse(f.get("Hm_unsent_"+c.id)||"[]")}catch(d){b=[]}if(b.length){a=a.replace(/^https?:\/\//,"");for(var e=0;e<b.length;e++)if(a.replace(/&u=[^&]*/,"")===b[e].replace(/&u=[^&]*/,"")){b.splice(e,1);break}b.length?f.set("Hm_unsent_"+c.id,k.stringify(b)):this.tb()}},tb:function(){f.remove("Hm_unsent_"+
c.id)},tc:function(){var b=this,d;try{d=k.parse(f.get("Hm_unsent_"+c.id)||"[]")}catch(e){d=[]}if(d.length)for(var g=function(d){a.log(l.la+"//"+d,function(a){b.cb(a)})},m=0;m<d.length;m++)g(d[m])},Oa:function(){return Math.round(+new Date/1E3)%65535}};return new b})();var A=h.z,B=h.load;c.pt&&B([A.protocol,"//ada.baidu.com/phone-tracker/insert_bdtj?sid=",c.pt].join(""));})();
